name: Deploy Frontend

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build & Push Image to ECR
      env:
        ECR_REGISTRY: 950899811193.dkr.ecr.us-east-1.amazonaws.com
        ECR_REPOSITORY: san/frontend
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Update Kubeconfig
      run: |
        aws eks update-kubeconfig --region us-east-1 --name <YOUR_EKS_CLUSTER_NAME>

    - name: Delete old secret (if exists)
      run: |
        kubectl delete secret ecr-regcred --ignore-not-found=true

    - name: Create new ECR Pull Secret
      run: |
        kubectl create secret docker-registry ecr-regcred \
        --docker-server=950899811193.dkr.ecr.us-east-1.amazonaws.com \
        --docker-username=AWS \
        --docker-password="$(aws ecr get-login-password --region us-east-1)"

    - name: Patch Deployment with new image
      env:
        IMAGE: 950899811193.dkr.ecr.us-east-1.amazonaws.com/san/frontend:${{ github.sha }}
      run: |
        kubectl set image deployment/frontend server=$IMAGE

    - name: Apply manifests (safe â€“ no patching service/serviceAccount)
      run: |
        kubectl apply -f kubernetes-manifests/frontend.yaml
